// src/pages/admin/realtime/DisasterMessageData.js

export const initialMessageData = [
  {
    id: "MSG-2026-010",
    category: "안전안내",
    type: "기상",
    sender: "전주시청",
    content: "오늘 08:19 전주지역 대설주의보 발효. 내집 앞 눈치우기 및 출근길 대중교통 이용, 차량 운행 시 안전거리를 확보하시기 바랍니다.",
    region: "전라북도 전주시",
    dateTime: "2026-01-23 08:19:00",
    isVisible: true,
  },
  {
    id: "MSG-2026-009",
    category: "안전안내",
    type: "실종자",
    sender: "전북경찰청",
    content: "완산구에서 실종된 박영희(여, 75세)씨를 찾습니다 - 155cm, 50kg, 남색 패딩, 검정바지, 자주색 유모차 vo.la/abcd / ☎182",
    region: "전라북도 전주시 완산구",
    dateTime: "2026-01-22 15:30:45",
    isVisible: true,
  },
  {
    id: "MSG-2026-008",
    category: "안전안내",
    type: "화재",
    sender: "전주시청",
    content: "전주시 덕진구 팔복동 인근 공장 화재 발생. 인근 주민은 창문을 닫고 외출을 자제하며, 이 지역을 우회하여 주시기 바랍니다.",
    region: "전라북도 전주시 덕진구",
    dateTime: "2026-01-20 11:12:30",
    isVisible: true,
  },
  {
    id: "MSG-2026-007",
    category: "안전안내",
    type: "기상",
    sender: "전주시청",
    content: "오늘 10시 전주시 미세먼지(PM-10) 주의보 발효. 실외활동 자제, 마스크 착용 등 건강관리에 유의하시기 바랍니다.",
    region: "전라북도 전주시",
    dateTime: "2026-01-18 10:05:12",
    isVisible: true,
  },
  {
    id: "MSG-2026-006",
    category: "안전안내",
    type: "교통통제",
    sender: "전주시청",
    content: "모래내시장 인근 도로 공사로 인해 편도 1개 차로 통제 중. 차량 정체가 예상되오니 가급적 우회 도로를 이용 바랍니다.",
    region: "전라북도 전주시 덕진구",
    dateTime: "2026-01-15 09:00:00",
    isVisible: true,
  },
  {
    id: "MSG-2026-005",
    category: "안전안내",
    type: "실종자",
    sender: "전북경찰청",
    content: "덕진구에서 실종된 이철수(남, 12세)군을 찾습니다 - 150cm, 노란색 후드티, 청바지, 흰색 운동화 vo.la/efgh / ☎182",
    region: "전라북도 전주시 덕진구",
    dateTime: "2026-01-12 18:22:10",
    isVisible: true,
  },
  {
    id: "MSG-2026-004",
    category: "안전안내",
    type: "기상",
    sender: "전주시청",
    content: "전주지역 한파경보 지속. 수도계량기 동파 주의, 독거노인 안부 확인 등 건강 및 시설물 관리에 유의 바랍니다.",
    region: "전라북도 전주시",
    dateTime: "2026-01-10 06:00:00",
    isVisible: true,
  },
  {
    id: "MSG-2026-003",
    category: "안전안내",
    type: "기타",
    sender: "전주시청",
    content: "전주시 평생학습 한마당 개최 안내. 1.15.(목) 전주종합경기장 일원. 주차 혼잡이 예상되오니 대중교통 이용 바랍니다.",
    region: "전라북도 전주시",
    dateTime: "2026-01-08 14:00:00",
    isVisible: true,
  },
  {
    id: "MSG-2026-002",
    category: "긴급재난",
    type: "화재",
    sender: "전주소방서",
    content: "[긴급재난] 전주 한옥마을 인근 상가 화재 발생. 현재 진압 중이며 인근 방문객은 안전한 곳으로 대피하십시오.",
    region: "전라북도 전주시 완산구",
    dateTime: "2026-01-05 22:45:12",
    isVisible: true,
  },
  {
    id: "MSG-2026-001",
    category: "안전안내",
    type: "실종자",
    sender: "전북경찰청",
    content: "전주시 전역에서 배회 중인 치매 어르신 김순자(여, 82세)씨를 찾습니다 - 회색 가디건, 검정 고무신 vo.la/ijkl / ☎182",
    region: "전라북도 전주시",
    dateTime: "2026-01-01 13:10:05",
    isVisible: true,
  }
];